version: '3'
services:
  mTab:
    image: itushan/php74:1.3
    container_name: mTabServer
    ports:
      - "3300:80"
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: root
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: mtaber
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
    restart: always
    networks:
      - my-network
networks:
  my-network:
    driver: baota_net

